# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f84f500b9a7c65d195224eb53d0637c11544826f49bba055a538780ed76afc14b282a17504bb3927fbcf05cec198dadd32e2935b32977b8a69d23a3b29da289

test:
  secret_key_base: 0d2d9601cb2b74d77950c65de1603c20cfa9bd80bc1f6391bf2eac4be278f1feb4a4d0b2b8b212b64467e99b1a15e9565783e6ca9644c5ab6921855c6e7c7267

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
